# Generated by Django 4.0.4 on 2022-05-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
