# Generated by Django 4.0.1 on 2022-05-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_product_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
